name: basic-workflow
on:
  push:
  workflow_dispatch:

jobs:
  basic-action:
    runs-on: ubuntu-latest
    name: Basic Github Action
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Run My Actions
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
